#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DW_USER WITH PASSWORD '$DW_PASSWORD';
    CREATE DATABASE $DW_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DW_DB_NAME TO $DW_USER;
    ALTER DATABASE $DW_DB_NAME OWNER TO $DW_USER;
EOSQL
